import type { Cultura, Praga, Doenca, Nutriente } from "@/shared/types";

export const CULTURAS: Cultura[] = [
  {
    id: "soja",
    nomePopular: "Soja",
    nomeCientifico: "Glycine max",
    familiaBotanica: "Fabaceae",
    cicloProdutivoMin: 90,
    cicloProdutivoMax: 160,
    descricao: "Principal oleaginosa do Brasil, rica em proteínas e óleos vegetais. Cultivada em larga escala no Centro-Oeste e Sul do país.",
    categoria: "oleaginosas",
    fasesFenologicas: ["Germinação", "Emergência", "Desenvolvimento vegetativo", "Floração", "Enchimento de grãos", "Maturação"],
    temperaturaMin: 20,
    temperaturaMax: 30,
    precipitacaoMin: 450,
    precipitacaoMax: 800,
    necessidadeLuz: "Pleno sol, fotoperíodo curto (dia curto). Necessita de 12-14 horas de luz para florescimento adequado.",
    tipoSolo: "Argiloso a franco-argiloso, bem drenado, pH entre 5,5 e 6,5, rico em matéria orgânica.",
    epocasPlantio: ["Outubro a dezembro (safra normal)", "Janeiro a fevereiro (safrinha)"],
    produtividadeMedia: "3.500 a 5.000 kg/ha (grãos)",
  },
  {
    id: "milho",
    nomePopular: "Milho",
    nomeCientifico: "Zea mays",
    familiaBotanica: "Poaceae",
    cicloProdutivoMin: 90,
    cicloProdutivoMax: 150,
    descricao: "Cereal de grande importância econômica, utilizado para alimentação humana, animal e produção de biocombustível.",
    categoria: "graos",
    fasesFenologicas: ["Germinação", "Plântula", "Desenvolvimento vegetativo", "Pendoamento", "Polinização", "Enchimento de grãos", "Maturação fisiológica"],
    temperaturaMin: 18,
    temperaturaMax: 32,
    precipitacaoMin: 500,
    precipitacaoMax: 800,
    necessidadeLuz: "Pleno sol, fotoperíodo neutro. Necessita de alta luminosidade para boa produtividade.",
    tipoSolo: "Franco a franco-argiloso, bem drenado, pH entre 5,5 e 7,0.",
    epocasPlantio: ["Setembro a novembro (safra de verão)", "Janeiro a fevereiro (safrinha)"],
    produtividadeMedia: "10.000 a 14.000 kg/ha (grãos)",
  },
  {
    id: "tomate",
    nomePopular: "Tomate",
    nomeCientifico: "Solanum lycopersicum",
    familiaBotanica: "Solanaceae",
    cicloProdutivoMin: 90,
    cicloProdutivoMax: 130,
    descricao: "Hortaliça fruto de grande valor comercial, amplamente consumida in natura e industrializada.",
    categoria: "hortalicas",
    fasesFenologicas: ["Germinação", "Muda", "Transplante", "Crescimento vegetativo", "Floração", "Frutificação", "Maturação"],
    temperaturaMin: 15,
    temperaturaMax: 30,
    precipitacaoMin: 400,
    precipitacaoMax: 700,
    necessidadeLuz: "Pleno sol ou meia sombra. Fotoperíodo de dia longo favorece crescimento vegetativo.",
    tipoSolo: "Franco a franco-argiloso, bem drenado, pH entre 5,5 e 7,0, rico em matéria orgânica.",
    epocasPlantio: ["Outubro a dezembro (plantio de mudas)", "Fevereiro a abril (transplante)"],
    produtividadeMedia: "60 a 120 t/ha (fruto fresco)",
  },
  {
    id: "cafe",
    nomePopular: "Café",
    nomeCientifico: "Coffea arabica",
    familiaBotanica: "Rubiaceae",
    cicloProdutivoMin: 730,
    cicloProdutivoMax: 1095,
    descricao: "Cultura perene de grande importância econômica para o Brasil, principal produtor mundial de café.",
    categoria: "outros",
    fasesFenologicas: ["Germinação", "Muda", "Formação", "Produção", "Floração", "Granação", "Maturação", "Colheita"],
    temperaturaMin: 18,
    temperaturaMax: 28,
    precipitacaoMin: 1200,
    precipitacaoMax: 2000,
    necessidadeLuz: "Pleno sol, fotoperíodo de dia curto para indução floral. Necessita de alta luminosidade.",
    tipoSolo: "Argiloso a franco-argiloso, pH entre 5,5 e 6,5, boa drenagem e fertilidade.",
    epocasPlantio: ["Abril a junho (plantio de inverno)", "Outubro a dezembro (plantio de verão)"],
    produtividadeMedia: "3 a 5 sacas/ha (60 kg)",
  },
  {
    id: "cana",
    nomePopular: "Cana-de-açúcar",
    nomeCientifico: "Saccharum officinarum",
    familiaBotanica: "Poaceae",
    cicloProdutivoMin: 365,
    cicloProdutivoMax: 540,
    descricao: "Principal matéria-prima para produção de açúcar e etanol no Brasil.",
    categoria: "outros",
    fasesFenologicas: ["Brotação", "Perfilhamento", "Crescimento", "Maturação", "Colheita"],
    temperaturaMin: 20,
    temperaturaMax: 35,
    precipitacaoMin: 1200,
    precipitacaoMax: 1800,
    necessidadeLuz: "Pleno sol, fotoperíodo neutro.",
    tipoSolo: "Argiloso a franco-argiloso, pH entre 5,5 e 6,5, alta fertilidade.",
    epocasPlantio: ["Setembro a novembro (plantio de cana-planta)", "Após colheita (soca)"],
    produtividadeMedia: "80 a 120 t/ha (colmo)",
  },
  {
    id: "algodao",
    nomePopular: "Algodão",
    nomeCientifico: "Gossypium hirsutum",
    familiaBotanica: "Malvaceae",
    cicloProdutivoMin: 150,
    cicloProdutivoMax: 200,
    descricao: "Fibra natural de grande importância têxtil, também utilizada para extração de óleo.",
    categoria: "fibrosas",
    fasesFenologicas: ["Germinação", "Plântula", "Vegetativo", "Botão floral", "Floração", "Capulho", "Abertura"],
    temperaturaMin: 20,
    temperaturaMax: 35,
    precipitacaoMin: 700,
    precipitacaoMax: 1300,
    necessidadeLuz: "Pleno sol, fotoperíodo de dia longo.",
    tipoSolo: "Argiloso a franco-argiloso, pH entre 5,5 e 7,0, bem drenado.",
    epocasPlantio: ["Outubro a dezembro (safra principal)"],
    produtividadeMedia: "1.500 a 2.000 kg/ha (fibra)",
  },
  {
    id: "arroz",
    nomePopular: "Arroz",
    nomeCientifico: "Oryza sativa",
    familiaBotanica: "Poaceae",
    cicloProdutivoMin: 100,
    cicloProdutivoMax: 150,
    descricao: "Cereal base da alimentação de mais da metade da população mundial.",
    categoria: "graos",
    fasesFenologicas: ["Germinação", "Plântula", "Perfilhamento", "Elongação", "Espigamento", "Floração", "Maturação"],
    temperaturaMin: 20,
    temperaturaMax: 30,
    precipitacaoMin: 1000,
    precipitacaoMax: 2000,
    necessidadeLuz: "Pleno sol, fotoperíodo de dia curto.",
    tipoSolo: "Argiloso a arenoso, pH entre 5,0 e 6,5, boa drenagem.",
    epocasPlantio: ["Outubro a dezembro (safra de verão)", "Fevereiro a março (safrinha)"],
    produtividadeMedia: "5.000 a 8.000 kg/ha (grãos)",
  },
  {
    id: "feijao",
    nomePopular: "Feijão",
    nomeCientifico: "Phaseolus vulgaris",
    familiaBotanica: "Fabaceae",
    cicloProdutivoMin: 65,
    cicloProdutivoMax: 100,
    descricao: "Leguminosa fundamental na dieta brasileira, rica em proteínas e fibras.",
    categoria: "graos",
    fasesFenologicas: ["Germinação", "Emergência", "Vegetativo", "Floração", "Formação de vagens", "Enchimento", "Maturação"],
    temperaturaMin: 16,
    temperaturaMax: 28,
    precipitacaoMin: 300,
    precipitacaoMax: 500,
    necessidadeLuz: "Pleno sol, fotoperíodo de dia curto.",
    tipoSolo: "Franco a argiloso, pH entre 6,0 e 7,0, boa drenagem e fertilidade.",
    epocasPlantio: ["Agosto a outubro (seca)", "Novembro a fevereiro (chuvas)", "Fevereiro a abril (inverno)"],
    produtividadeMedia: "1.500 a 2.500 kg/ha (grãos)",
  },
];

export const PRAGAS: Praga[] = [
  {
    id: "lagarta-do-cartucho",
    nome: "Lagarta-do-cartucho",
    nomeCientifico: "Spodoptera frugiperda",
    culturas: ["milho", "sorgo", "arroz"],
    sintomas: "Folhas com orifícios irregulares, cartucho com excrementos escuros, plantas com aspecto de 'janelamento'. Em infestações severas, destruição completa do cartucho.",
    nivelRisco: "alto",
    metodoControle: "Inseticidas biológicos (Bt), inseticidas químicos registrados, controle biológico com Trichogramma. Monitoramento semanal recomendado.",
    prevencao: "Plantio em época adequada, rotação de culturas, manutenção de inimigos naturais, monitoramento regular.",
  },
  {
    id: "broca-do-cafe",
    nome: "Broca-do-café",
    nomeCientifico: "Hypothenemus hampei",
    culturas: ["cafe"],
    sintomas: "Orifício circular na base do fruto, grãos brocados com galerias internas, queda prematura de frutos, redução da qualidade do café.",
    nivelRisco: "critico",
    metodoControle: "Colheita no prazo, repasse e varreção, controle biológico com Beauveria bassiana, inseticidas registrados.",
    prevencao: "Colheita eficiente, eliminação de frutos remanescentes, monitoramento com armadilhas.",
  },
  {
    id: "mosca-branca",
    nome: "Mosca-branca",
    nomeCientifico: "Bemisia tabaci",
    culturas: ["tomate", "soja", "algodao"],
    sintomas: "Folhas com manchas amarelas, presença de insetos brancos na face inferior, fumagina (fungo negro), transmissão de vírus.",
    nivelRisco: "alto",
    metodoControle: "Inseticidas sistêmicos, controle biológico com Encarsia formosa, óleos minerais e vegetais.",
    prevencao: "Uso de variedades resistentes, armadilhas amarelas, eliminação de plantas hospedeiras.",
  },
  {
    id: "percevejo-marrom",
    nome: "Percevejo-marrom",
    nomeCientifico: "Euschistus heros",
    culturas: ["soja", "milho", "feijao"],
    sintomas: "Grãos com manchas e deformações, vagens com puncturas, redução do peso dos grãos, transmissão de patógenos.",
    nivelRisco: "alto",
    metodoControle: "Inseticidas piretróides e neonicotinóides, controle biológico com Telenomus podisi.",
    prevencao: "Monitoramento com pano-de-batida, rotação de culturas, destruição de soqueira.",
  },
  {
    id: "nematoide-cisto",
    nome: "Nematoide-de-cisto",
    nomeCientifico: "Heterodera glycines",
    culturas: ["soja"],
    sintomas: "Reboleiras com plantas amareladas e raquíticas, sistema radicular reduzido com cistos brancos ou marrons, morte prematura.",
    nivelRisco: "critico",
    metodoControle: "Rotação com culturas não hospedeiras, uso de cultivares resistentes, nematicidas.",
    prevencao: "Análise de solo antes do plantio, uso de sementes certificadas, rotação de culturas.",
  },
];

export const DOENCAS: Doenca[] = [
  {
    id: "ferrugem-soja",
    nome: "Ferrugem Asiática da Soja",
    agenteCausal: "Phakopsora pachyrhizi",
    tipo: "fungica",
    culturas: ["soja"],
    condicoesFavoraveis: "Temperatura entre 15-28°C, umidade relativa acima de 75%, períodos de molhamento foliar prolongados.",
    sintomas: "Pústulas marrom-avermelhadas na face inferior das folhas, desfolha precoce, redução severa da produtividade.",
    controle: "Fungicidas triazóis e estrobilurinas, aplicação preventiva, monitoramento semanal.",
    prevencao: "Plantio em época adequada, uso de cultivares resistentes, vazio sanitário.",
  },
  {
    id: "requeima-tomate",
    nome: "Requeima do Tomate",
    agenteCausal: "Phytophthora infestans",
    tipo: "fungica",
    culturas: ["tomate"],
    condicoesFavoraveis: "Temperatura entre 10-25°C, alta umidade, chuvas frequentes, neblina.",
    sintomas: "Manchas aquosas nas folhas que evoluem para lesões necróticas com bordas amareladas, podridão dos frutos.",
    controle: "Fungicidas cúpricos e sistêmicos, eliminação de plantas doentes, melhora da ventilação.",
    prevencao: "Uso de cultivares resistentes, espaçamento adequado, irrigação por gotejamento.",
  },
  {
    id: "mancha-angular-feijao",
    nome: "Mancha Angular do Feijão",
    agenteCausal: "Pseudocercospora griseola",
    tipo: "fungica",
    culturas: ["feijao"],
    condicoesFavoraveis: "Temperatura entre 16-28°C, alta umidade relativa, orvalho frequente.",
    sintomas: "Manchas angulares delimitadas pelas nervuras, cor cinza a marrom, desfolha precoce em casos severos.",
    controle: "Fungicidas triazóis, aplicação no início dos sintomas.",
    prevencao: "Sementes certificadas, rotação de culturas, cultivares resistentes.",
  },
  {
    id: "brusone-arroz",
    nome: "Brusone do Arroz",
    agenteCausal: "Magnaporthe oryzae",
    tipo: "fungica",
    culturas: ["arroz"],
    condicoesFavoraveis: "Temperatura entre 24-28°C, alta umidade, ventos, adubação nitrogenada excessiva.",
    sintomas: "Lesões elípticas com centro cinza e bordas marrons nas folhas, pescoço da panícula apodrecido (brusone do pescoço).",
    controle: "Fungicidas sistêmicos, aplicação preventiva na fase de espigamento.",
    prevencao: "Cultivares resistentes, adubação equilibrada, evitar excesso de nitrogênio.",
  },
  {
    id: "mosaico-comum-feijao",
    nome: "Mosaico Comum do Feijão",
    agenteCausal: "Bean common mosaic virus (BCMV)",
    tipo: "viral",
    culturas: ["feijao"],
    condicoesFavoraveis: "Presença de pulgões vetores, temperaturas amenas, plantios próximos a fontes de inóculo.",
    sintomas: "Mosaico verde-claro e verde-escuro nas folhas, bolhosidade, deformação foliar, nanismo.",
    controle: "Não há controle curativo. Eliminar plantas doentes e controlar pulgões vetores.",
    prevencao: "Sementes certificadas livres de vírus, controle de pulgões, cultivares resistentes.",
  },
];

export const NUTRIENTES: Nutriente[] = [
  {
    id: "nitrogenio",
    nome: "Nitrogênio",
    simbolo: "N",
    tipo: "macronutriente",
    funcao: "Componente de proteínas, clorofila e ácidos nucleicos. Essencial para o crescimento vegetativo e produção de biomassa.",
    sintomasDeficiencia: "Clorose (amarelecimento) das folhas mais velhas, começando pelas pontas. Crescimento reduzido, plantas raquíticas.",
    sintomasExcesso: "Crescimento vegetativo excessivo, plantas suculentas e suscetíveis a pragas e doenças, atraso na maturação.",
    fontesFertilizantes: "Ureia, sulfato de amônio, nitrato de amônio, nitrocálcio.",
  },
  {
    id: "fosforo",
    nome: "Fósforo",
    simbolo: "P",
    tipo: "macronutriente",
    funcao: "Componente de ATP, ácidos nucleicos e fosfolipídios. Essencial para desenvolvimento radicular e transferência de energia.",
    sintomasDeficiencia: "Coloração arroxeada nas folhas (antocianinas), crescimento reduzido, sistema radicular deficiente.",
    sintomasExcesso: "Induz deficiência de zinco e ferro, reduz absorção de micronutrientes.",
    fontesFertilizantes: "Superfosfato simples, superfosfato triplo, fosfato monoamônico (MAP), fosfato diamônico (DAP).",
  },
  {
    id: "potassio",
    nome: "Potássio",
    simbolo: "K",
    tipo: "macronutriente",
    funcao: "Regulação osmótica, abertura e fechamento de estômatos, ativação enzimática, qualidade dos frutos.",
    sintomasDeficiencia: "Necrose nas bordas das folhas mais velhas (escaldadura), frutos de baixa qualidade, plantas suscetíveis a estresses.",
    sintomasExcesso: "Induz deficiência de magnésio e cálcio, desequilíbrio nutricional.",
    fontesFertilizantes: "Cloreto de potássio, sulfato de potássio, nitrato de potássio.",
  },
  {
    id: "calcio",
    nome: "Cálcio",
    simbolo: "Ca",
    tipo: "macronutriente",
    funcao: "Estrutura da parede celular, divisão celular, sinalização, neutralização de ácidos orgânicos.",
    sintomasDeficiencia: "Necrose das folhas novas e meristemas, podridão apical em frutos (tomate), deformação de folhas jovens.",
    sintomasExcesso: "Eleva pH do solo, induz deficiência de boro e magnésio.",
    fontesFertilizantes: "Calcário calcítico, gesso agrícola, nitrato de cálcio.",
  },
  {
    id: "magnesio",
    nome: "Magnésio",
    simbolo: "Mg",
    tipo: "macronutriente",
    funcao: "Componente central da clorofila, ativação enzimática, translocação de fotoassimilados.",
    sintomasDeficiencia: "Clorose internerval nas folhas mais velhas (nervuras verdes, entre-nervuras amarelas).",
    sintomasExcesso: "Raro em condições naturais, pode interferir na absorção de potássio.",
    fontesFertilizantes: "Calcário dolomítico, sulfato de magnésio, kieserita.",
  },
  {
    id: "ferro",
    nome: "Ferro",
    simbolo: "Fe",
    tipo: "micronutriente",
    funcao: "Síntese de clorofila, transporte de elétrons, componente de enzimas respiratórias.",
    sintomasDeficiencia: "Clorose internerval nas folhas jovens (nervuras verdes, entre-nervuras amarelas a brancas), comum em solos alcalinos.",
    sintomasExcesso: "Manchas marrons nas folhas, redução do crescimento, toxidez em solos alagados.",
    fontesFertilizantes: "Sulfato ferroso, quelatos de ferro (EDTA, DTPA, EDDHA).",
  },
  {
    id: "zinco",
    nome: "Zinco",
    simbolo: "Zn",
    tipo: "micronutriente",
    funcao: "Ativação enzimática, síntese de auxinas, metabolismo de carboidratos e proteínas.",
    sintomasDeficiencia: "Encurtamento de entrenós, folhas pequenas e deformadas, clorose internerval em folhas jovens.",
    sintomasExcesso: "Clorose, inibição do crescimento, toxidez em solos ácidos com alto teor de zinco.",
    fontesFertilizantes: "Sulfato de zinco, óxido de zinco, quelatos de zinco.",
  },
  {
    id: "boro",
    nome: "Boro",
    simbolo: "B",
    tipo: "micronutriente",
    funcao: "Formação da parede celular, desenvolvimento reprodutivo, translocação de açúcares.",
    sintomasDeficiencia: "Morte de gemas apicais, deformação de folhas jovens, frutos defeituosos, rachaduras em raízes.",
    sintomasExcesso: "Necrose nas bordas das folhas, toxidez em solos com excesso de boro.",
    fontesFertilizantes: "Bórax, ácido bórico, ulexita.",
  },
];

// ─── Culturas adicionais ───────────────────────────────────────────────────
export const CULTURAS_EXTRAS: Cultura[] = [
  {
    id: "trigo",
    nomePopular: "Trigo",
    nomeCientifico: "Triticum aestivum",
    familiaBotanica: "Poaceae",
    cicloProdutivoMin: 100,
    cicloProdutivoMax: 150,
    descricao: "Cereal de inverno, base para produção de farinha, pão e massas. Cultivado principalmente no Sul do Brasil.",
    categoria: "graos",
    fasesFenologicas: ["Germinação", "Plântula", "Afilhamento", "Elongação", "Espigamento", "Floração", "Maturação"],
    temperaturaMin: 10,
    temperaturaMax: 25,
    precipitacaoMin: 450,
    precipitacaoMax: 700,
    necessidadeLuz: "Pleno sol, fotoperíodo de dia longo para espigamento.",
    tipoSolo: "Franco a argiloso, pH entre 5,5 e 6,5, boa drenagem.",
    epocasPlantio: ["Maio a julho (inverno no Sul)"],
    produtividadeMedia: "2.500 a 4.500 kg/ha (grãos)",
  },
  {
    id: "mandioca",
    nomePopular: "Mandioca",
    nomeCientifico: "Manihot esculenta",
    familiaBotanica: "Euphorbiaceae",
    cicloProdutivoMin: 270,
    cicloProdutivoMax: 540,
    descricao: "Raiz tuberosa de grande importância alimentar e industrial, adaptada a solos pobres e clima tropical.",
    categoria: "outros",
    fasesFenologicas: ["Brotação", "Crescimento vegetativo", "Tuberização", "Maturação", "Colheita"],
    temperaturaMin: 20,
    temperaturaMax: 35,
    precipitacaoMin: 600,
    precipitacaoMax: 1500,
    necessidadeLuz: "Pleno sol, fotoperíodo neutro.",
    tipoSolo: "Arenoso a franco-arenoso, pH entre 5,5 e 7,0, boa drenagem.",
    epocasPlantio: ["Setembro a novembro (primavera)", "Fevereiro a março (início das chuvas)"],
    produtividadeMedia: "20 a 35 t/ha (raízes frescas)",
  },
  {
    id: "batata",
    nomePopular: "Batata",
    nomeCientifico: "Solanum tuberosum",
    familiaBotanica: "Solanaceae",
    cicloProdutivoMin: 90,
    cicloProdutivoMax: 130,
    descricao: "Tubérculo de grande importância alimentar, terceiro alimento mais consumido no mundo.",
    categoria: "hortalicas",
    fasesFenologicas: ["Brotação", "Emergência", "Crescimento vegetativo", "Tuberização", "Maturação", "Colheita"],
    temperaturaMin: 10,
    temperaturaMax: 25,
    precipitacaoMin: 500,
    precipitacaoMax: 800,
    necessidadeLuz: "Pleno sol, fotoperíodo de dia longo favorece tuberização.",
    tipoSolo: "Franco a franco-arenoso, pH entre 5,0 e 6,0, boa drenagem.",
    epocasPlantio: ["Julho a agosto (inverno/primavera)", "Janeiro a fevereiro (outono)"],
    produtividadeMedia: "25 a 45 t/ha (tubérculos)",
  },
  {
    id: "cebola",
    nomePopular: "Cebola",
    nomeCientifico: "Allium cepa",
    familiaBotanica: "Amaryllidaceae",
    cicloProdutivoMin: 100,
    cicloProdutivoMax: 150,
    descricao: "Hortaliça bulbosa de grande importância culinária e medicinal, amplamente cultivada no Brasil.",
    categoria: "hortalicas",
    fasesFenologicas: ["Germinação", "Muda", "Crescimento vegetativo", "Bulbificação", "Maturação", "Colheita"],
    temperaturaMin: 13,
    temperaturaMax: 28,
    precipitacaoMin: 350,
    precipitacaoMax: 600,
    necessidadeLuz: "Pleno sol, fotoperíodo de dia longo para bulbificação.",
    tipoSolo: "Franco a argiloso, pH entre 6,0 e 7,0, boa drenagem.",
    epocasPlantio: ["Março a maio (outono/inverno no Sul)", "Julho a agosto (inverno no Nordeste)"],
    produtividadeMedia: "25 a 50 t/ha (bulbos)",
  },
  {
    id: "alface",
    nomePopular: "Alface",
    nomeCientifico: "Lactuca sativa",
    familiaBotanica: "Asteraceae",
    cicloProdutivoMin: 45,
    cicloProdutivoMax: 75,
    descricao: "Hortaliça folhosa de ciclo curto, amplamente consumida in natura. Adaptada a cultivo em campo e hidroponia.",
    categoria: "hortalicas",
    fasesFenologicas: ["Germinação", "Muda", "Crescimento vegetativo", "Formação de cabeça", "Colheita"],
    temperaturaMin: 10,
    temperaturaMax: 25,
    precipitacaoMin: 300,
    precipitacaoMax: 600,
    necessidadeLuz: "Pleno sol a meia sombra, fotoperíodo de dia curto favorece crescimento vegetativo.",
    tipoSolo: "Franco a argiloso, pH entre 6,0 e 7,0, rico em matéria orgânica.",
    epocasPlantio: ["Ano todo (com irrigação)", "Outono/inverno (clima ameno)"],
    produtividadeMedia: "20 a 35 t/ha (folhas frescas)",
  },
  {
    id: "sorgo",
    nomePopular: "Sorgo",
    nomeCientifico: "Sorghum bicolor",
    familiaBotanica: "Poaceae",
    cicloProdutivoMin: 90,
    cicloProdutivoMax: 140,
    descricao: "Cereal resistente à seca, utilizado para alimentação animal, produção de silagem e biocombustível.",
    categoria: "graos",
    fasesFenologicas: ["Germinação", "Plântula", "Crescimento vegetativo", "Emborrachamento", "Floração", "Enchimento de grãos", "Maturação"],
    temperaturaMin: 18,
    temperaturaMax: 38,
    precipitacaoMin: 300,
    precipitacaoMax: 700,
    necessidadeLuz: "Pleno sol, fotoperíodo de dia curto para florescimento.",
    tipoSolo: "Argiloso a arenoso, pH entre 5,5 e 7,0, tolera solos pobres.",
    epocasPlantio: ["Janeiro a março (safrinha)", "Outubro a dezembro (safra)"],
    produtividadeMedia: "4.000 a 8.000 kg/ha (grãos)",
  },
  {
    id: "eucalipto",
    nomePopular: "Eucalipto",
    nomeCientifico: "Eucalyptus spp.",
    familiaBotanica: "Myrtaceae",
    cicloProdutivoMin: 1825,
    cicloProdutivoMax: 2555,
    descricao: "Espécie florestal de rápido crescimento, utilizada para produção de celulose, carvão vegetal e madeira.",
    categoria: "outros",
    fasesFenologicas: ["Mudas", "Plantio", "Crescimento inicial", "Crescimento rápido", "Maturação", "Colheita"],
    temperaturaMin: 15,
    temperaturaMax: 35,
    precipitacaoMin: 700,
    precipitacaoMax: 1500,
    necessidadeLuz: "Pleno sol, fotoperíodo neutro.",
    tipoSolo: "Argiloso a arenoso, pH entre 4,5 e 6,5, tolerante a solos pobres.",
    epocasPlantio: ["Outubro a dezembro (início das chuvas)"],
    produtividadeMedia: "30 a 50 m³/ha/ano (madeira)",
  },
];

// Exporta todas as culturas combinadas
export const TODAS_CULTURAS: Cultura[] = [...CULTURAS, ...CULTURAS_EXTRAS];
